apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway-app
  labels:
    app: api-gateway-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-gateway-app
  template:
    metadata:
      labels:
        app: api-gateway-app
    spec:
      containers:
        - name: api-gateway-app
          image: 2022mt93326/api-gateway:0.0.1-SNAPSHOT
          imagePullPolicy: Always
          ports:
            - containerPort: 8181

---
apiVersion: v1
kind: Service
metadata:
  name: cloud-gateway-svc
spec:
  ports:
    - port: 80
      targetPort: 8181
      protocol: TCP
  selector:
    app: api-gateway-app