apiVersion: v1
kind: ConfigMap
metadata:
  name: mongo-db-config
data:
  host: mongodb-service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: quotation-service-app
  labels:
    app: quotation-service-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: quotation-service-app
  template:
    metadata:
      labels:
        app: quotation-service-app
    spec:
      containers:
        - name: quotation-service-app
          image: 2022mt93326/quotation-management-system:0.0.1-SNAPSHOT
          imagePullPolicy: Always
          ports:
            - containerPort: 9098
          env:
            - name: MONGO_HOST
              valueFrom:
                configMapKeyRef:
                  name: mongo-db-config 
                  key: host

---
apiVersion: v1
kind: Service
metadata:
  name: quotation-service-svc
spec:
  ports:
    - port: 80
      targetPort: 9098
      protocol: TCP
  selector:
    app: quotation-service-app